const int NodesNumber = 7;
const int PopulationSize = 100;//(int) std::pow(2, NodesNumber);
const int NumberOfIterations = 10;
const double LambdaFitness = 0.5;
const int NotSolutionPenalty = 5;
const int TourneySize = 2;
const int PopulationAfterSelection = PopulationSize;
const double MutationRate = 0.01;
const double CrossOverParticipationRate = 0.1;